### ISSUE TITLE
My-Position

### ISSUE THREAD

**Issue by Robhorry** [loick111/homebridge-rfxcom-accessories#3]
%-Position doesnt work realy well. Maybe, the Problem ist the opening/close Duration which is different with Shutters (uptime is slower than downtime). Additionally, the My-Button is Missing.

Is it possible to link a defined % (eg 50%) to the My-Position Command?

Best Regards
Rob

**Comment by loick111** [comment]
Hi @Robhorry,
I added the possibility to define the closing time different from the opening time. It should be better now for your use case.

For the MyButton, I'm not sure that's something we want to have in HomeKit.
I think you should have a look on "Shortcuts" to create a shortcut that will easily set a preset position of your shutter. 

https://support.apple.com/en-gb/guide/shortcuts/welcome/ios

**Comment by Robhorry** [comment]
Thx for that, i will give it a try.
The Preset „My“ is programmed in the Hardware.
The RFXCOM has a command, next to many other (like the program comand)
How do i use this command with Shortcuts?
I will post a screenshot of the commands of the RFXmngr later.

**Comment by loick111** [comment]
Thank you for your interest and feedback regarding the functionality of the blinds. I wanted to clarify the philosophy behind the implementation and address your request.

The primary goal of the implementation is to allow users to set a percentage on HomeKit, and the blinds will automatically adjust to the desired position based on that percentage. This approach emphasises automation and eliminates the need for manual control through a stop button or preset.

Regarding your request to link a defined percentage to the "My-Position" command, it's important to note that the "My" preset is typically programmed in the hardware itself. 

Please keep in mind that the current focus of the implementation is on automation and percentage-based control. While the suggestions for manual control are valid, they may not align with the initial philosophy of the project.
