### ISSUE TITLE
Does this plugin support the Forest Shuttle RF curtains?

### ISSUE THREAD

**Issue by HuLu-web** [loick111/homebridge-rfxcom-accessories#5]
I have added several Somfy devices to my RFXcom transmitter and also two Forest Shuttle RF curtains.
These curtains have been added with the following device information:

* Forest Shuttle RF
* Protocol = BlindsT7
* 00.04.01.0 / unit all   Small curtain
* 00.04.02.0 / unit all   Large curtain
By the way: unit all has to be selected, individual codes (e.g. 0 or 1) do not work

They work perfectly when transmitting open and close commands using the RFXManager programm.

I have tried to add them to the Homebridge-RFXcom-Accessories plugin as RFY devices (knowing they are not Somfy the chance of succes was near to zero) and as on/off switch with the following definition:
* type           Blinds1
* subtype     7
* id               0004020 all

I've tried several variations on these settings, but I can't get the curtains to activate.
Hence the question whether this plugin support the Forest Shuttle RF curtains?

**Environment:**

* Plugin Version 2,4,0
* Hoobs Version 4.1.17
* Homebridge Version 1.3.6
* Node.js Version 16.13.1
* NPM Version 8.1.2
* Operating System Raspbian 5.10.63

**Comment by loick111** [comment]
To be followed in the issue #10.
