### ISSUE TITLE
When HomeBridge reboots, the RFXCom sends a command to all screens/motors to open.

### ISSUE THREAD

**Issue by danielpetrovic** [loick111/homebridge-rfxcom-accessories#9]
**Is your feature request related to a problem? Please describe:**
When HomeBridge/Docker reboots, the RFXCom sends a command to all Somfy curtains/motors to open, but in HomeKit/HomeBridge it shows as if all curtains are closed. I need to open/close after every reboot to get the proper state inside HomeKit.

**Describe the solution you'd like:**
Remember last state before reboot and don't send any command on boot. If last state cannot be preserved on reboot, an option to change the default boot mode which signal is send to the motors.

**Describe alternatives you've considered:**
Change default boot mode to close all curtains, so state in HomeKit and physical state is the same, after reboot.

**Comment by loick111** [comment]
Pre-release v2.5.0 has been created.
